### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by MrFireFrog** [wKovacs64/hibp#204]
Hello. Thank you for the project.
Am use for React, but have problem with CORS
How to fix it?
[https://skr.sh/i/170221/DZ713XeI.jpg](url)

**Comment by wKovacs64** [comment]
Hey @MrFireFrog,

Thanks for your interest in the library. Based on your screenshot, I would guess you aren't providing an API key to the `breachedAccount` function as I don't see `hibp-api-key` in the request headers. Troy Hunt (creator and maintainer of the Have I Been Pwned service) began requiring paid API keys for certain parts of the service back in 2019, including the one you're calling here. Once you've obtained an API key, you can pass it as an option to `breachedAccount` like so:

```js
breachedAccount('yourAccountName', { apiKey: 'your-api-key' })
```

If you're already doing that, there might be something else going on and we can troubleshoot further. Let me know!

---

Troy's reasoning: https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/
Where to get an API key: https://haveibeenpwned.com/API/Key
