### ISSUE TITLE
Change pwnedPasswordRange to resolve with array of objects

### ISSUE THREAD

**Issue by wKovacs64** [wKovacs64/hibp#25]
Continuing the discussion from https://github.com/wKovacs64/hibp/pull/23#issuecomment-370452713 , should `pwnedPasswordRange` resolve to more easily consumable JS instead of the raw text of the response? Is there any use case where a consumer would want/need to access the plain text? 🤔 

CC @danieladams456

**Comment by danieladams456** [comment]
Race condition #24 :D

**Comment by wKovacs64** [comment]
> The one thing you lose (I think) is the ability to do a `result.includes(searchString)`.  You instead have to do an `array.filter(anonymousFunction)` [like this](https://github.com/wKovacs64/hibp/blob/122aecb7057a28187f85f8c1cc6bea382fd19aa6/src/pwnedPassword.js#L46).  I would argue it follows principle of least surprise as you have to declare which field you want to search.  Are there any other concerns I'm not thinking of?

I think `filter` makes more sense than `includes`. It's also more accurate as `includes` would pick up substrings, perhaps unintentionally. It does come at a performance cost, though.

**Comment by danieladams456** [comment]
Even with `filter()`, latency is still mainly spent on the http call.  To be at the level where filter would matter CPU instructions wise, you'd be at pretty much at abuse level of the API.

**Comment by wKovacs64** [comment]
Agreed, should be negligible.
