### ISSUE TITLE
LogoType

### ISSUE THREAD

**Issue by rcurrier666** [wKovacs64/hibp#26]
Can you explain what the `LogoType` field in the `breach` data is (or could be) used for? I know what SVG and JPG are, but to what data do they refer? I don't see any reference to it in the source code.

**Comment by wKovacs64** [comment]
Hey @rcurrier666, thanks for your interest in the project.

The data comes from Troy Hunt's [*Have I been pwned?*](https://haveibeenpwned.com/) service and this library is just an interface to it, so you won't find this (or any other fields) in the source code here, aside from examples (potentially). Unfortunately, it doesn't appear he has updated his [API documentation](https://haveibeenpwned.com/API/v2#BreachModel) to reflect the `LogoType` field in the `breach` model. The only guess I could wager is perhaps he's also going to add another field with an image URL to the company's logo and `LogoType` is metadata for it, or something of that nature?

(Side note: looks like there is an `IsActive` field that has not made it into his documentation either.)

You could post on his [UserVoice feedback site](https://haveibeenpwned.uservoice.com/), maybe somebody (or Troy himself) will know.

Hopefully that helps! Closing this issue as it is nothing I can solve in this project.
