### ISSUE TITLE
Is there timeout on fetch?

### ISSUE THREAD

**Issue by andrzej-woof** [wKovacs64/hibp#302]
I couldn't find anything in sources so I assume there's no timeout on doing fetch on HIBP API?
It would be nice to have an option to define it in config, as well as some default timeout.

**Comment by wKovacs64** [comment]
There's not currently a timeout on the fetch calls (other than built-in browser defaults). I'll think it over, but my initial reaction is to avoid adding an API for this. You can solve this in consuming code with stuff like `Promise.race` and `setTimeout` (it won't cancel the request like an `AbortController` would, but it's something). 🤔

**Comment by wKovacs64** [comment]
@andrzej-woof Sorry this took so long (you probably don't care anymore), but I finally broke down and added built-in timeout support. 😛
