### ISSUE TITLE
Error - "You may need an appropriate loader to handle this file type"

### ISSUE THREAD

**Issue by mrjackwills** [wKovacs64/hibp#321]
Not sure if this in an appropriate place to report this issue, but, I am coming back to a Vue2 + Vuetify project, which I haven't touched in about six months.

On running npm run serve, I am met with this message;
```
ERROR  Failed to compile with 1 error

error  in ./node_modules/hibp/dist/esm/api/haveibeenpwned/fetchFromApi.mjs

Module parse failed: Unexpected token (18:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    * should never happen.
|    */
>   retryAfterSeconds;
| 
|   constructor(retryAfter, message, options) {
...
```

The only method that I am importing from your library is 
```
import { pwnedPassword } from 'hibp';
```
and if I remove this import, I no longer receive the error

Again, I am not sure exactly where, or why, this error is occurring, but as I say I have changed nothing in my project for the past 6 months

EDIT: This occurs when using hibp v11.1.0, using v11.0.0 I do not get any errors and all works fine

**Comment by mrjackwills** [comment]
this is using Node v16.16.0, it's an (annoying) webpack + typscript frontend build - meaning their are many layers of config which go over my head

**Comment by wKovacs64** [comment]
I wonder if it's targeting older browsers (like IE 11). You could try this, perhaps?

```
// vue.config.js

module.exports = {
  transpileDependencies: ['hibp']
}
```

Source: https://vuetifyjs.com/en/getting-started/browser-support/#vue-cli

**Comment by mrjackwills** [comment]
> I wonder if it's targeting older browsers (like IE 11). You could try this, perhaps?
> 
> ```
> // vue.config.js
> 
> module.exports = {
>   transpileDependencies: ['hibp']
> }
> ```
> 
> Source: https://vuetifyjs.com/en/getting-started/browser-support/#vue-cli

Yup, re-installed v11.1.0, and added hibp to my transpileDependencies, now working as expected

**Comment by wKovacs64** [comment]
Glad to hear that worked!
