### ISSUE TITLE
Errors in web workers or extension background threads

### ISSUE THREAD

**Issue by ArcadeRenegade** [wKovacs64/hibp#456]
Looks like all API methods fail when trying to call them from a web worker or extension background threads since `window` is `undefined`.

Looking at `src/api/web-fetch.ts` it looks like it assumes it is running in a NodeJS environment if `window` is `undefined`.

Perhaps a more accurate check to see if native fetch is available can be simply `'fetch' in globalThis`

**Comment by wKovacs64** [comment]
Sounds reasonable. PRs welcome 🙂 or I'll get to it when I can.

**Comment by wKovacs64** [comment]
@ArcadeRenegade Can you try `hibp@experimental` and see if it resolves your issue? 🙏

**Comment by wKovacs64** [comment]
> @ArcadeRenegade Can you try `hibp@experimental` and see if it resolves your issue? 🙏

I think the one I published when I wrote that was busted, you may need to force reinstall the `experimental` tag if you were quick to test it (or install `hibp@0.0.0-dev.d74e2ad2` directly). 😛

**Comment by ArcadeRenegade** [comment]
@wKovacs64 I just tested and I can confirm it works in an extension background thread / web worker.

**Comment by ArcadeRenegade** [comment]
@wKovacs64 thanks for looking into this!

**Comment by wKovacs64** [comment]
Sweet, thanks for confirming!

**Comment by wKovacs64** [comment]
@all-contributors please add @ArcadeRenegade for bug reports.

**Comment by wKovacs64** [comment]
@ArcadeRenegade Fix has been released in v14.1.0. Thanks again.
