### ISSUE TITLE
Cannot use hibp modules in React Native development mode

### ISSUE THREAD

**Issue by yelworc** [wKovacs64/hibp#72]
I'm trying to use hibp in a React Native project, but I'm getting this error when importing the module and starting the app in dev mode:

```
In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.

    Object.assign @ Object.es6.js:37:14
    <unknown> @ hibp.js:23:14
    loadModuleImplementation @ require.js:292:4
    guardedLoadModule @ require.js:186:11
    metroRequire @ require.js:115:72
    […]
```

As far as I can see, this is caused by [this RN polyfill](https://github.com/facebook/react-native/blob/0.57-stable/Libraries/polyfills/Object.es6.js#L37), triggered by [this line](https://github.com/wKovacs64/hibp/blob/06ee9d593772f1b0eb8a2a650c8c4a09914efef7/src/internal/haveibeenpwned/axiosInstance.ts#L16) in hibp, which passes `false` as the second parameter to `Object.assign` because `navigator` is an object in this scenario (the navigator global of the browser attached for debugging).

Like the error message says, hibp isn't doing anything wrong here; but I guess this would be fairly simple to prevent, by modifying the `Object.assign` call to always pass an object?

**Comment by wKovacs64** [comment]
Thanks for the detailed bug report, @yelworc - outstanding!

I just published the fix in `hibp@7.5.1`. Let me know if this doesn't resolve it for you.

**Comment by yelworc** [comment]
Wow, quick turnaround! This did indeed fix the problem for me. Thank you!

**Comment by wKovacs64** [comment]
Great! Thanks again.
